= This Week in JBoss - 11 June 2020
Don Naro
v1.0, 2020-06-11
:tags: quarkus, kogito, sso, infinispan

Welcome to another edition of the JBoss Editorial where we gather news from our communities and explore developments from our projects.

== Mandrel 

There has been some exciting 
link:https://developers.redhat.com/blog/2020/06/05/mandrel-a-community-distribution-of-graalvm-for-the-red-hat-build-of-quarkus/[news about Mandrel]. 
You've likely heard of this by now but, in his announcement post, Mark explains how Red Hat has worked 
with the GraalVM community to create a distribution of OpenJDK with GraalVM's native-image 
capabilities for producing native executables.


== AI vs COVID-19

link:https://developers.redhat.com/blog/2020/06/09/ai-vs-covid-19-how-java-helps-nurses-and-doctors-in-this-fight/[A recent DevNation Tech Talk] with 
a very topical subject looks at how OptaPlanner has helped keep medical staff and patients safer with advanced planning algorithms. 
It's nice to see Java play a role in improving things for those who are in the front lines of the pandemic.

== In the Community

Eric Schnabell keeps his Cloud-native development series going with a look at 
link:https://www.schabell.org/2020/06/cloud-native-development-on-remote-containers.html[example use cases for using remote container platforms as development environments].

The Infinispan blog has seen a flurry of activity in the run up to the 11.0.0.Final release, which 
should be available real soon now. In the meantime, you can read about some of the things that will be 
available in Infinispan 11 here:

* William Burns link:https://infinispan.org/blog/2020/06/09/offheap-resize/[shares some enhancements to Infinispan's Off Heap implementation] 
that simplify configuration and improve performance.

* Pedro Ruivo link:https://infinispan.org/blog/2020/06/05/xsite-improvements/[explains how Infinispan uses vector clocks] 
to detect conflicts with asynchronous cross-site replication as well as the strategy for resolving conflicts.

Over at the Strimzi blog, there is link:https://strimzi.io/blog/2020/06/09/mirror-maker-2-eventhub/[another installment of the series around Mirror Maker]. 
Check out the post for mirroring to Azure Event Hub using Mirror Maker 2.

== Release Roundup

* link:https://quarkus.io/blog/quarkus-1-5-final-released/[Quarkus 1.5.0.Final has arrived], which brings a fast-jar packaging format along with several new extensions.

* link:https://wildfly.org/news/2020/06/08/WildFly20-Final-Released/[WildFly 20 has been released] with numerous bug fixes and updates. 

* link:https://www.keycloak.org//2020/06/keycloak-1002-released.html[Keycloak 10.0.2 is here]. Read all about it. 

That's it for this week's editorial. Thanks for reading and see you next time.
