= This Week in JBoss: 14 January 2021
Romain Pelisse
v1.1, 2021-01-14
:tags: wildfly, camel, keycloak, teiid, springboot, tekton, kubernetes, codeready, quarkus, jgroups

Welcome to the first installment of our JBoss Editorial for 2021! And to start the year, we have a brand new major release of the core product of the JBoss community! Yes, Wildfly 22 is out!

== Wildfly 22 and Camel 3.7

Yes! We have a brand new major version of Wildfly! link:https://www.wildfly.org/news/2021/01/13/WildFly22-Final-Released/[Wildfly 22 is out!].

This release includes support for use of log4j2 in applications, new base health and metrics subsystems to provide server observability for users who don't need the application instrumentation that comes with MicroProfile Health and Metrics, and a number of other features related to management, provisioning, messaging and security. Plus numerous bug fixes, enhancements and component upgrades.

On top of that, there is also an updated version of the new tech-preview WildFly Preview distribution. This will allow the community have a look at what Wildfly developers are doing for Jakarta EE 9 support, along with other changes in the server architecture that are expected to appear later in 2021.

Wildfly 22 is already a nice treat, but we also have link:https://camel.apache.org/blog/2020/12/Camel37-Whatsnew/[Camel 3.7], which also quite exciting, and fortunately for all of us, Claus Ibsen has published a review of what he called link:http://www.davsclaus.com/2020/12/apache-camel-37-lts-released-fastest.html[the fastest Camel ever!] So, go check it out if you want to know more about this camel release.

== Tech bytes

A few interesting technical articles came out in the last weeks, so we'll try to catch you up with three of them here. First, we have an excellent one from Bela Ban on link:http://belaban.blogspot.com/2020/12/running-jgroups-raft-as-service.html[running JGroups raft as a service]. It's very hands on post, focusing on getting everything running. Then we have a longer walkthrough to let you experiment on link:https://blog.ramon-gordillo.dev/2020/12/spring-boot-embedded-cache-with-infinispan-in-kubernetes/[using Spring boot embedded cache with Infinispan on Kubernetes]. Certainly, worth a look, isn't it? The last one is, of course, on Quarkus, because Quarkus is, as it should, all the rage lately. In this article, Clément Escoffier took the time to explain some of the link:https://quarkus.io/blog/magic-control[magic beneath Quarkus and Vert.x] and why this is the kind magic you to have as a developer.

== Evangelist's Corner

As always, our very own Eric Schabell has been busy in the few last weeks and released a steady stream of new content. First, he published link:https://www.schabell.org/2021/01/codeready-containers-installing.html[part4 - Installing business automation operator] of his series on CodeReady containers. He then revisited the link:https://www.schabell.org/2020/12/codeready-containers-exploring-home-loan-mortgage-process.html[Home loan mortgage process using CodeReady Containers]. Still on the topic of CodeReady Containers, he provided a link:https://www.schabell.org/2021/01/codeready-containers-howto-setup-openshift-46-on-local-machine.html[How to setup the OpenShift Container Platform 4.6 on your local machine] follow by a tutorial on link:https://www.schabell.org/2020/12/codeready-containers-building-hr-process-with-openshift-operator.html[Building a Human Resources Process with an OpenShift Operator]

== Releases, releases, releases...

As always, the JBoss community has been quite active in the last weeks, and more than a few project releases new version (including the forementionned Wildfly 22 and Apache Camel 3.7):
* link:https://www.wildfly.org/news/2021/01/13/WildFly22-Final-Released/[Wildfly 22 Final released!]
* link:https://www.keycloak.org//2020/12/keycloak-1201-released.html[Keycloak 12.0.1 released]
* https://camel.apache.org/blog/2020/12/Camel37-Whatsnew/[Apache Camel 3.7]
* link:http://teiid.blogspot.com/2021/01/teiid-spring-boot-170-released.html[Teiid Spring Boot 1.7.0 Released]

== Decaf

You want to break from Java programming, but still learn something relevant to it? Well, take a look at this article on link:https://developers.redhat.com/blog/2021/01/13/getting-started-with-tekton-and-pipelines/[Getting started with Tekton and Pipelines]. It's more than likely to pique your interest.

_That's all for today! Please join us again in two weeks for another installment of our JBoss editorial! Stay safe and healthy in the meantime._
