= This Week in JBoss - 11 August 2022
Don Naro
2022-08-11
:tags: quarkus, kubernetes, java, jakarta, infinispan, wildfly, cloud-native, openshift, kogito, drools, keycloak

Hi everyone!
It's great to be back and bringing you another edition of the JBoss Editorial.
As always there's a lot of exciting news and updates from JBoss communities so let's dive in.

== Release roundup

[square]
* link:https://infinispan.org/blog/2022/08/09/infinispan-14[Infinispan 14.0.0.CR1]
* link:https://www.keycloak.org/2022/07/keycloak-1901-released.html[Keycloak 19.0.1]
* link:https://vertx.io/blog/eclipse-vert-x-4-3-3/[Eclipse Vert.x 4.3.3]
* link:https://resteasy.dev/2022/08/02/resteasy-6.1.0-release/[RESTEasy 6.1.0.Final]
* link:https://quarkus.io/blog/quarkus-2-11-2-final-released/[Quarkus 2.11.2.Final] (`CVE-2022-2466` is still ongoing)
* link:https://www.wildfly.org/news/2022/08/05/WildFly27-Alpha4-Released/[WildFly 27 Alpha4]
* link:https://blog.kie.org/2022/08/kogito-1-25-0-released.html[Kogito 1.25.0]

== WildFly Maven plugin to create container images

link:https://www.wildfly.org/news/2022/08/04/wildfly-maven-docker/[Use the wildfly-maven-plugin to create a Docker image of your application], by By Jeff Mesnil

Jeff explains how to use the `wildlfy-maven-plugin` and the new WildFly runtime image to build container images.
The WildFly Maven plugin, currently in beta with Final planned for WildFly 27, offers a new, and very compelling, architecture to control the full runtime from the application `pom.xml`.
Developers control the full customization of WildFly using feature packs, packaging scripts, and other artifacts.
This approach ensures that the runtime fits the user’s application.
Creating a container image is simply a matter of putting it in a runtime image that contains OpenJDK.

The WildFly team are starting an open conversation to bring additional synergies between the Docker and S2I images for WildFly that could benefit the whole community.
The team are aiming to bring new capabilities, additional architectures (in particular `linux/arm64`), and newer versions of the JDK to all WildFly images.
Be sure to check out Jeff's post and find out how you can get involved!

== Jakarta Bean Validation

link:http://www.mastertheboss.com/java-ee/validation/test/[Getting started with Jakarta Bean Validation], by Francesco Marchioni

Francesco takes a look at the Jakarta Bean Validation specification which allows you to express constraints on your model and create custom ones in an extensible way.
His detailed post shows you how to write a constraint once and use it in any application layer.
Given that Bean validation is layer agnostic, meaning that you can use the same constraint from the presentation to the business model layer.

== Kogito Rules (Drools) with Java Inheritance

link:https://blog.kie.org/2022/08/kogito-rules-drools-with-java-inheritance.html[Kogito Rules (Drools) with Java Inheritance], by Jeff Taylor

In this article, Jeff explains how Kogito rules services can reason over application domain model facts that are represented using plain old Java objects, or POJOs, that use standard Java inheritance.
DRL rules files can use POJOs as well as client applications that call the Kogito rules services.

Jeff explores two approaches for sharing Java subclasses between a Kogito rules service and a client application.
The first approach isolates objects from each subclass into a JSON array while the second approach uses Jackson inheritance annotations to embed objects from each subclass for REST API calls that serialize and deserialize POJOs to and from JSOn.

== Welcome Václav Muzikář!

link:https://www.keycloak.org/2022/08/vaclav[New Keycloak maintainer: Václav Muzikář], by Bruno Oliveira

The Keycloak team has a new community maintainer!
Hearty welcome to Václav Muzikář.

== YouTube videos

From unmissable demos to brilliant chat about the latest Java trends, the JBoss community has some great video content for you:

* link:https://youtu.be/Urj1X60H6YY[Quarkus Insights #98: Using Minecraft as an Observability client]
* link:https://youtu.be/nH-27gOp0h4[Quarkus Insights #97: Qute with Quarkus]
* link:https://youtu.be/kdasoBPOWUQ[Quarkus Insights #96: Quarkus Q&A]
* link:https://youtu.be/9DMAkrM_gOA[MLOps with Flyte with Samhita Alla]

== See you next time

_Hope you enjoyed this edition. Please join us again in two weeks for our JBoss editorial!_
