= This Week in JBoss: 26 June 2020
Jason Porter
2020-06-26
:tags: quarkus, data grid, camel, editorial,

Here we are, once again at the close of June.
Another summer has begun, albeit a little different than most.
I hope everyone is safe, healthy, and doing well.
There have been some very interesting blogs posted in the past couple of weeks that we'll discuss in this edition, as well as a few releases.

Operators in Kubernetes provide an extension point for the platform.
They follow a pattern allowing you to manage resources and applications within the cluster.
An operator can be either namespace-scoped or cluster-scoped.
Did you know, however, that you can convert between the two?
That is exactly what Abhishek Koserwal details in six steps over on the https://developers.redhat.com/blog/2020/06/26/migrating-a-namespace-scoped-operator-to-a-cluster-scoped-operator/[Red Hat Developer blog].
Abhishek walks you through a basic example and provides the full example as a GitHub repo.
Read the article for more information, and reasons why you may want or need to switch between the different scopes.

Multitenancy may be something you deal with everyday, or it may be something you're looking at adding to your current application base.
Either way, dealing with persistence can be tricky.
Tenants must not see each other's data, but be allowed to operate simultaneously.
Your application must also perform well while still being easy to maintain.
Rhuan Rocha has started a two part series on how to use JPA with Multitenancy over on the Red Hat Developer blog.
https://developers.redhat.com/blog/2020/06/15/jakarta-ee-multitenancy-with-jpa-on-wildfly-part-1/[The first entry] details the problem and presents a possible solution using WildFly and EJBs.
Expect the next installment to look more at Hibernate and JPA solutions.

Effortlessly building a native application is of course, one of the amazing capabilities of Quarkus.
However, when it comes to debugging, a native Quarkus application makes debugging **very** difficult.
A large part of this is the optimizations that happen to create that quick, small, native binary.
This debugging complication hasn't gone unnoticed.
Andrew Dinn has been working on this problem.
He contributed a solution where the debug information is embedded with in the native image and can be access with `gdb`.
If you'd like to learn more about the solution, https://developers.redhat.com/blog/2020/06/25/debugging-graalvm-native-images-using-gdb/[read Andrew's blog entry].

Continuing with the Quarkus theme, Durgesh Anaokar wrote about https://developers.redhat.com/blog/2020/06/19/develop-and-test-a-quarkus-client-on-red-hat-codeready-containers-with-red-hat-data-grid-8-0/[developing and testing a Quarkus Red Hat Data Grid client using Red Hat CodeReady Containers].
Durgesh details installing CRC (Red Hat Code Ready Containers) and Data Grid on OpenShift 4 as well as running the client.
Naturally, his project code is hosted in GitHub, you'll find that link in his blog entry.

Red Hat now has images, Universal Base Images to be exact, of OpenJDK (8 and 11) in Red Hat Enterprise Linux 8.2.
A Universal Base Image (UBI) is an OCI-compliant container base OS image with runtime and language support that can be used as the base for Docker images and Podman/Buildah images.
These will allow you to deploy and build supportable applications on Red Hat OpenShift and RHEL.
It also includes a number of additional user-space packages over a base UBI.
Read more about this https://developers.redhat.com/blog/2020/06/25/introducing-the-red-hat-build-of-the-openjdk-universal-base-images-now-in-red-hat-enterprise-linux-8-2/[over at Red Hat Developers].

If you have been following, you'll know the Infinispan team has been hard at work on Infinispan 11.
They are proud to announce that https://infinispan.org/blog/2020/06/15/infinispan-11/[Inifinspan 11.0.0. Final has been released]!
A number of improvements and features have been added to this release including clustering, CLI, Hot Rod Client improvements, non-blocking internals, and others.

Along with that new Infinispan release, you can now deploy a https://infinispan.org/blog/2020/06/16/native-server-announce/[natively compiled version of the Infinispan server]!
The memory footprint is only 286MB.
There are also native Quarkus extensions for your Quarkus based applications.

Not to be left out of the cloud native party, Apache Camel is https://developers.redhat.com/blog/2020/06/18/camel-k-1-0-the-serverless-integration-platform-goes-ga/[announcing the GA release of Apache Camel K 1.0].
This release includes tooling, connectors, and integrations with Knative.
This is a great step forward for doing integrations with a small footprint.

Lastly, https://developers.redhat.com/blog/2020/06/17/red-hat-jboss-enterprise-application-platform-expansion-pack-1-0-released/[Red Hat JBoss Enterprise Application Platform Expansion Pack 1.0] was recently released.
This is a patch that adds MicroProfile capabilities to JBoss EAP.
There are some policy changes you will need to be aware of, but you find links to all of thosewithin the announcement.

Thanks again for being with us on another JBoss Editorial!




