= This Week in JBoss - 11 February 2021
Jason Porter
2021-02-11
:tags: quarkus, wildfly, kogito, openshift, vertx

Here we are again, it's been two weeks and we're into the second month of 2021!
How quickly times flies!
In this edition, expect to find release information, blog posts, and general updates from around the JBoss Community.

== Releases!

* https://quarkus.io/blog/quarkus-1-11-2-final-released/[Quarkus 1.11.2.Final] is the second maintenance release for the Quarkus 1.11 branch. The notable bug fix with this version is updating to Hibernate ORM 5.4.27.SP1 which fixes a potential data loss issue. Please see the https://github.com/quarkusio/quarkus/releases/tag/1.11.2.Final[full changelog for more info].
* https://quarkus.io/blog/quarkus-1-11-3-final-released/[Quarkus 1.11.3.Final] is a quick bug fix release that focused on a regression making it impossible to build native executables if your project was using both RESTEasy and OpenTracing. https://github.com/quarkusio/quarkus/releases/tag/1.11.3.Final[Please see the full changelog] for more information.
* https://www.wildfly.org//news/2021/02/11/WildFly2201-Released/[Wildfly 22.0.1] has been released, about a month after 22.0.
* https://vertx.io/blog/eclipse-vert-x-4-0-2/[Vert.x 4.0.2 released] recently. The 4.0.1 release also happened, but contained potential memory leaks and the team decided not to announce it and proceed with another quick release to fix the issues. https://github.com/vert-x3/wiki/wiki/4.0.2-Release-Notes[Please view the release notes for more details].
* https://blog.kie.org/2021/02/kogito-tooling-0-8-3-released.html[Kogito Tooling 0.8.3 released] a few days ago. With the release of 0.8.1, the Kogito team released their official version of the BPMN and DMN standalone editors. This release builds on that and continues to allow you to embed the editor within your application. It also allows you to open DMN 1.1 and 1.3 assets. The post also contains a list of bugs squashed

We would certainly like to thank all those who helped complete these releases!
Each team is grateful for the help from the community.

== Highlights from the blogosphere

Eric Schabell published a migration guide for a traditional JBoss BPM application running either within a VM or on bare-metal to running inside containers using OpenShift Container Platform.
In https://www.schabell.org/2021/03/4-easy-steps-for-migrating-projects-to-openshift-container-platform.html[his post he breaks the migration down into four steps].
I won't detail them all here, but the steps are very easy and you should be able to get up and running quickly on your own laptop, even without having some of the tech installed previously!

https://blog.kie.org/2021/02/improvements-of-project-authoring-in-business-central.html[Abhishek Kumar discussed project authoring improvements within Business Central recently on the KIE Blog].
The features he discusses are:
. Opening projects directly with a URL
. Changing the default asset page size
. Security permissions for project screen tools and tabs

Each of these help users in the authoring process within Business Central through either ease of use or security!

Still on the KIE Blog, https://blog.kie.org/2021/01/how-to-use-a-pmml-file-in-dmn-editor-vscode.html[Yeser Amer demonstrates how to use PMML models in the DMN Editor].
PMML support was released with version 0.7.0.
PMML is an XML file describing a predictive model often generated by data mining or AI algorithms.
The support for this format within the VSCode plugin was recently released and follows the same usage patterns as those found within Business Central, so it may very well be familiar to some.

A number of blogs about Quarkus sprang up over the past couple of weeks!

Firstly, Georgios Andrianakis discusses https://quarkus.io/blog/resteasy-reactive-faq/[achieving massive performance without headaches] in a RESTEasy application on Quarkus using RESTEasy Reactive.
He talks about the different models, how to use them, the best way to get performance out of each model, and why this will likely becoming the default model within RESTEasy on Quarkus in the near future.

Clement Escoffier https://quarkus.io/blog/getting-started-amqp/[helps us get started with AMQP in Quarkus] with an in-depth demo similar to using Kafka.
He walks you through the basics and gives you a running project which he steps through to show you all the basics.

Over on the Red Hat Developers Blog, Eric Deandrea shows us a very cool trick, or maybe the power of Quarkus's Spring compatibility, about running a Spring Boot application on Quarkus without changing a single line of Java code!
It is definitely worth the read, https://developers.redhat.com/blog/2021/02/09/spring-boot-on-quarkus-magic-or-madness/[head on over to check it out]!

If you missed the announcement about Quarkus remote development, be sure to read up about it by Daniel Oh https://developers.redhat.com/blog/2021/02/11/enhancing-the-development-loop-with-quarkus-remote-development/[on the Red Hat Developer Blog].
Using a mutable-jar package, you can deploy onto OpenShift and continue to develop remotely without having to build a new container and push every time you want to see a change!
What an amazing way to build on the cloud and make sure everything works correctly without having slow downs!

Yeray Borges of the Wildfly team https://www.wildfly.org/news/2021/02/01/Bootable-jar-jkube-clustering-openshift/[demonstrates how to deploy a bootable Wildfly application jar which caches the HTTP session state].
It's a useful option allowing you to build and test locally and then push to OpenShift with minimal changes ensuring your application still works in the cloud.

Lastly, Mario Fusco and Edson Yanaga have a presentation from a recent DevNation Live about designing a Java API.
Check it out over on https://developers.redhat.com/devnation/tech-talks/design-java-apis[the Red Hat Developer blog].
Certainly worth the watch if you develop APIs in Java (which should be most of you).

Thanks for being with us for another edition of the JBoss Weekly Editorial.

