= This Week in JBoss - January 13th 2022
Stefan Sitani
2022-01-13
:tags: quarkus, java, resteasy, camel, reactive, panache, hibernate, event-driven, netty, kubernetes

Happy new year, everyone! Welcome to the first JBoss weekly editorial of 2022.
Enjoy our pick of the latest news and interesting reads from around the JBoss community.

== Releases, releases, releases!

Here are the releases from the JBoss Community for this edition:

[square]
* link:https://quarkus.io/blog/quarkus-2-6-0-final-released/[Quarkus 2.6.0]

* link:https://camel.apache.org/blog/2021/12/camel-quarkus-release-2.6.0/[Camel Quarkus 2.6.0]

* link:https://debezium.io/blog/2021/12/16/debezium-1.8-final-released/[Debezium 1.8.0]

* link:https://vertx.io/blog/eclipse-vert-x-3-9-12/[Eclipse Vert.x 3.9.12] and link:https://vertx.io/blog/eclipse-vert-x-4-2-3/[4.2.3]

* link:https://in.relation.to/2022/01/05/hibernate-search-6-0-8-Final/[Hibernate Search 6.0.8]

== Articles, Books, and Tutorials

New year, new content! Check out some of the recent articles about Java, Kubernetes, Quarkus, and more...

=== New Book: Reactive Systems in Java

link:https://www.oreilly.com/library/view/reactive-systems-in/9781492091714/[Reactive Systems in Java], by Clement Escoffier and Ken Finnigan

In their new book _Reactive Systems in Java_, Clement Escoffier and Ken Finnigan take an in-depth look at reactive systems design make applications responsive, elastic, and resilient, and
explore event-driven architectures as a flexible and composable option for designing distributed systems. Full of practical examples, their new book helps developers bring these approaches together when designing applications with Quarkus.

=== Simplify Java persistence using Quarkus and Hibernate Reactive

link:https://developers.redhat.com/articles/2022/01/06/simplify-java-persistence-using-quarkus-and-hibernate-reactive#[Simplify Java persistence using Quarkus and Hibernate Reactive] by Daniel Oh

Daniel Oh walks you through developing a reactive application with persistent data storage that leverages the benefits of simplified JPA implementation using the new extension for Hibernate Reactive with Panache.

=== Getting started with Netty

link:http://www.mastertheboss.com/jboss-frameworks/netty/jboss-netty-tutorial/?utm_source=rss&utm_medium=rss&utm_campaign=jboss-netty-tutorial[Getting started with Netty] by Francesco Marchioni

Francesco's tutorial introduces you to Netty a client/server framework that provides a simplified layer over non-blocking I/O networking. The introduction briefly describes the notable features that Netty provides. The first part of the tutorial section explains how you can create a simple echo server. The second part shows you how you can expand it by adding a separate Netty Client with its own Handler, and also demonstrates how to send a String between the client and the server over the event loop.

=== Why you should migrate your Java workloads to OpenShift

link:https://developers.redhat.com/articles/2022/01/07/why-you-should-migrate-your-java-workloads-openshift#[Why you should migrate your Java workloads to OpenShift] by Philip Hayes

In the first part of his two-part post series, Philip Hayes outlines the main benefits of migrating Java workloads to OpenShift and explores a number of tools available from Red Hat and from the Konveyor community project that are designed to help you transitions your Java workloads to the cloud with ease. Stay tuned for part 2 that will take an in-depth look at migrating a JBoss EAP application to OpenShift!

=== How to use Quarkus with the Service Binding Operator

link:https://developers.redhat.com/articles/2021/12/22/how-use-quarkus-service-binding-operator[How to use Quarkus with the Service Binding Operator] by Ioannis Kanellos

Ioannis Kanellos opens his article with a brief history of service binding solutions for Kubernetes developers and follows it up with a demonstration of a developer workflow centered around binding an external database service to an application in a cloud environment. With plenty of code examples and technical detail, Ioannis walks you through provisioning a database service, writing a Quarkus app for simplified data access with Hibernate with Panache, generating the service binding resources using the Service Binding Operator, and deploying your project to a containerized Kubernetes cluster running on your local machine.

=== Videos

Here's my pick of this week's YouTube videos:

* link:https://youtu.be/1_GUWDeQIsc[Drag and Drop your Quarkus Serverless App on the Developer Sandbox]
* link:https://youtu.be/1Rt7CPFodbE[Quarkus Insights #75: State of the Quarkus Ecosystem]


_That's all for today! Please join us again in two weeks for another round of our JBoss editorial!_
