= This Week in JBoss - June, 1st 2023
Romain Pelisse 2023-06-01
:tags: quarkus, java, jee, micro-profile, wildfly, ansible, kogito, keycloak

First and foremost! Dear readers, we want our opinion about the content of the editorial. We know filling up poll can be annoying, so you made as simple as possible... Please answer our **one question only** link:https://framadate.org/XbAltuQw4kQDY9At[poll on our editorial]! Thanks!

Two of the biggest stars of the JBoss ecosystem are for sure Quarkus and, of course, Wildfly, the application server that used to be called, well, JBoss! The last weeks have seen a lot of interesting content and news around those two projects, so we are going to focus this editorial on them. Buckle up, there is a ton of passionating stuff coming your way!

== Quarkus

The last two weeks have seen again quite a few interesting news, and content released, for the "Supersonic Subatomic Java" framework Quarkus! On top on the link:https://quarkus.io/blog/quarkus-3-1-0-final-released/[3.1.0.Final release] and the link:https://quarkus.io/blog/quarkus-3-0-4-final-released/[3.0.4.Final release] a new guide to migrate to those versions have been published: link:https://quarkus.io/blog/quarkus-3-upgrade/[Migration to Quarkus 3.0 is a breeze]! No reason to stay behind now, jump on board of Quarkus 3!

I'm also happy to mention that my guide on link:https://quarkus.io/guides/ansible[Automate Quarkus deployment with Ansible] has been added to the website. Hope it helps Quarkus user who wants to automate their deployment!

== Be The Boss of Wildfly

In the unlikely case, you have never heard of this website, Master The Boss, that has been around since forever, you have a chance to discover today. It has been publishing content on JBoss for over a decade and the articles published in the last week are pretty example of the site's richness.

First one we wanted to mention is link:https://www.mastertheboss.com/keycloak/google-social-login-with-keycloak/[KeyCloak Social Login Step-by-Step guide]. Keycloak is popular SSO software and social login is certainly worth a mention. Then come two articles more focused on Wildfly. The first one is link:https://www.mastertheboss.com/eclipse/eclipse-microservices/microprofile-lra-a-comprehensive-guide/[MicroProfile LRA: A Comprehensive Guide] and the second is link:https://www.mastertheboss.com/eclipse/jboss-tools/using-visual-studio-to-develop-and-manage-wildfly/[Using Visual Studio to develop and manage WildFly].

== Release roundup

As always the JBoss world is a thriving place thus the last got her fair share of releases:

[square]

* link:https://quarkus.io/blog/quarkus-3-1-0-final-released/[Quarkus 3.1.0.Final released]
* link:https://quarkus.io/blog/quarkus-3-0-4-final-released/[Quarkus 3.0.4.Final]
* link:https://www.wildfly.org//news/2023/05/23/WildFly2801-Released/[WildFly 28.0.1 is released!]
* link:https://blog.kie.org/2023/05/kogito-1-38-0-released.html[KOGITO 1.38.0 is released!]

== Decaf

Enough java? Too much jitters? Wants to peek outside the coffee cup for a sec? The decaf's section is here for you!

To stay on today's theme, we wanted to mention that my guide on link:https://quarkus.io/guides/ansible[Automate Quarkus deployment with Ansible] has been added to the project's website. I hope it helps Quarkus user who wants to automate their deployment! And note that there is also a link:https://www.wildfly.org/news/2023/01/10/ansible-wildfly/[Ansible collection (extension) dedicated to Wildfly].

A last note on Ansible, that may interest people of the community. There is a very cool new project called link:https://www.ansible.com/blog/getting-started-with-event-driven-ansible[Event Driven Ansible] using, behind the curtains, another cool project of the JBoss community: link:https://www.drools.org/[Drools]!

_That's all folks! Please join us again in two weeks for another round of our JBoss editorial!_
