= This Week in JBoss - December, 29th 2022
Romain Pelisse
2022-12-29
:tags: quarkus, java, jakarta ee, wildfly, ansible, keycloak

_Happy Holidays!_

_Welcome to our last installment of JBoss Editorial for 2022! As we are about to let this year behind us, it’s time to look back and review our biggest achievement of the past twelve months, but also look ahead to 2023 and what is as in store for the JBoss community!_

In the previous years, it was Mark Little who wrote this last editorial, often sharing his thoughts on the JBoss community accomplishments and the exciting challenges of the next year. Needless to say, I have impossible shoes to fill in for here! So, I’m not even trying to :), especially as I certainly don’t have the same overview that Mark has on our industry. Also, I will not list all of the milestones the JBoss community achieve. There were simply too many of them to do so, from link:https://quarkus.io/blog/road-to-quarkus-3/[Quarkus reaching its 200th release and its third major version], link:https://www.wildfly.org/news/2022/11/09/WildFly27-Final-Released/[Wildfly implementing the latest version of the Jakarta EE specification] or link:https://octoverse.github.com/2022/state-of-open-source[Keycloak named by GitHub one of the top projects in 2022]. The only one I could really discuss is the success of my own personal project, integrating as much as possible the JBoss community famous projects into Ansible (link:https://github.com/ansible-middleware/wildfly/[Wildfly], link:https://github.com/ansible-middleware/infinispan/[Infinispan], link:https://github.com/ansible-middleware/keycloak[Keycloak], and link:https://github.com/ansible-middleware/amq[AMQ]), both upstream (with the collection available on link:https://galaxy.ansible.com/search?deprecated=false&keywords=middleware_automation&order_by=-relevance&page=1[Ansible Galaxy]) and downstream (on link:https://console.redhat.com/ansible/automation-hub/?page_size=10&view_type=list&page=1&keywords=redhat%20java[Ansible Automation Hub] for Red Hat customers). One of those extensions is now even part, as a technical preview feature, of the latest release of link:https://developers.redhat.com/articles/2022/12/22/automate-jboss-web-server-deployment-red-hat-certified-content-collection-jws[Red Hat JWS]! But, once more, this is only one of the numerous achievements of this year.

This short inventory of mine is probably as incomplete as it is biased, but it does make my case: yet again, the JBoss community has been thriving, releasing new version often, and producing quality content (blogs, videos or presentation). I, for one, can’t wait to see what will come out of it next year, and if you are too, well, I have good news. You are already in the right place ;)! The JBoss Editorial will continue and will keep you inform, as much as we can, of everything happening!

_That’s all folks! Please join us again in two weeks for another installment of our JBoss editorial!_
