= This Week in JBoss - 26 January 2023
Don Naro
2023-26-01
:tags: ansible, quarkus, java, jbang, infinispan, wildfly, cloud-native, kia, keycloak, kafka

Hi everyone!
It's great to be back and bringing you another edition of the JBoss Editorial.
As always there's a lot of exciting news and updates from JBoss communities, so let's dive in.

== Release roundup

[square]

* https://quarkus.io/blog/quarkus-2-16-0-final-released/[Quarkus 2.16.0.Final]
* https://quarkus.io/blog/quarkus-3-0-0-alpha3-released/[Quarkus 3.0.0.Alpha3]
* https://www.wildfly.org/news/2023/01/18/WildFly2613-Released/[WildFly 26.1.3]
* https://www.keycloak.org/2023/01/keycloak-2003-released[Keycloak 20.0.3]
* https://infinispan.org/download/[Infinispan 14.0.6.Final]

== Deploying a WildFly cluster using Ansible

link:https://www.wildfly.org/news/2023/01/10/ansible-wildfly/[Deploying a WildFly 27.0.1 cluster using Ansible], by Romain Pelisse

Romain treats us to a brief demonstration that uses Ansible to effortlessly set up a WildFly cluster.
Romain uses a short, simple playbook that fully automates his deployment and really shows how Ansible collections can greatly simplify configuration and reduce the time it takes to create large clusters with hundreds of nodes.

== Listing Maven local artifacts with JBang

link:http://www.mastertheboss.com/java/how-to-list-maven-local-artifacts-using-jbang/[How to list Maven local artifacts using JBang], by Francesco Marchioni

I have to say I'm a huge fan of JBang.
What's not to love about an easy-to-use tool that makes scripting with Java a breeze?
When I noticed the title of Francesco's post, I clicked it immediately and dug right in.
It did not disappoint and showed a neat JBang CLI script that uses picocli libraries to find the Maven versions of an artifact in your local repository.

== A look at the Apache Kafka landscape

link:http://www.ofbizian.com/2023/01/apache-kafka-landscape.html[Apache Kafka Landscape], by Bilgin Ibryam

Bilgin's post is a great resource for anyone exploring the Apache Kafka ecosystem and provides a lot of time-saving data around various projects, tools, and services related to Kafka.

== Quickly deploying dashboards to GitHub pages

link:https://blog.kie.org/2023/01/deploying-dashbuilder-dashboards.html[Deploying Dashbuilder Dashboards], by William Siqueira

William delivers a snappy article that shows you how to publish Dashbuilder dashboards and easily make them available to users in almost no time at all.

== Quarkus native adopts adaptive GC policy

link:https://quarkus.io/blog/native-adopts-adaptive-gc-policy/[Quarkus Native adopts Adaptive GC policy], by Galder Zamarreño

Galder's informative post takes us through an examination of the recent change to the garbage collection policy for Quarkus native applications.
The change aligns with GraalVM's default "adaptive" GC policy to provide a better out of the box experience.
Galder shows us in spectacular detail how this change brings about more consistent and predictable runtime performance.

== Event-Driven Ansible Office Hours

link:https://github.com/ansible/event-driven-ansible#office-hours[Event-driven Ansible Office Hours]

Surely by now you've heard of Event-Driven Ansible but maybe you only have a rough idea of how the technology works?
Well, great news!

The team have started office hours to demo and explain how Event-Driven Ansible allows you to subscribe to an event-listening source and then quickly and easily automate tasks that respond to those events. Follow the link above to find the latest webinar and learn from the community.

== YouTube videos

Definitely catch the replay of link:https://youtu.be/qcjrGlRimYU[Quarkus Insights #115: What's new in Infinispan?] if you haven't already watched it.

Also check out Sean Cavanaugh's demo video, link:https://youtu.be/aqQq5vD8-n0[Getting started with Event-Driven Ansible and Ansible Rulebooks].

== See you next time

_Hope you enjoyed this edition. Please join us again in two weeks for our JBoss editorial!_
